docs(users): creating a user
itslanguage/itslanguage-docs pull request #11
Opened 2016-12-13 11:29 UTC by dcsiebe

Document creating a user using the rest api.

2016-12-13 14:40 UTC, Lehren requested changes

2016-12-13 14:40 UTC, Lehren commented on mkdocs.yml
> +    - 'Users': 'api/users.md'
`User`s takes the place of `Student`s right? If so remove the student files.

2016-12-13 14:40 UTC, Lehren commented on docs/api/users.md
> +powers can perform these calls.
Is creating a User the only thing possible? No getting or listing?

2016-12-13 14:56 UTC, dcsiebe commented on docs/api/users.md
> +powers can perform these calls.
I'll document listings later on ;)

2016-12-13 14:56 UTC, dcsiebe commented on mkdocs.yml
> +    - 'Users': 'api/users.md'
Not yes, eventually it will, I will then remove the students file.

2016-12-14 07:31 UTC, kvdb approved these changes

2016-12-14 07:31 UTC, kvdb commented on docs/api/users.md
> +  "firstName": "Najat",
Is he a relative of Garry?

2016-12-14 07:31 UTC, merged