Update speechchallenge fields
itslanguage/itslanguage-docs pull request #114
Opened 2019-06-25 14:37 UTC by joggienl

## Changed

- metadata was missing from the examples;
- Prettier was run on the `speech_challenges.md` file which happened unintentionally but changes are fine

## Added

- The language field was missing in the Speech Challenge api docs
- Prerequisites on when wanting to take the speech feedback challenge

2019-07-12 13:19 UTC, Red-mar commented on docs/api/speech_challenges.md
> +| `language`       | `string` | **Optional** Language of the challenge in ISO 639-2 format.          |
Sort of optional. If you don't specify you have no idea which model will be used (english at the moment) and you might get unexpected results.

2019-07-12 13:22 UTC, Red-mar commented on docs/api/speech_challenges.md
> +| `topic`          | `string` | **Optional** A question or topic serving as guidance to the student. |
Topic is not optional, even if you have an srt its-ws-server will not work without a topic.

2019-07-15 10:05 UTC, kvdb commented
Since Jogchum has his holidays feel free to implement your suggestions and merge yourself.

2019-08-23 20:05 UTC, kvdb requested changes

2019-08-23 20:05 UTC, kvdb commented on docs/api/speech_challenges.md
> +    "language": null,
```suggestion
    "language": "eng",
```

2019-08-23 20:05 UTC, kvdb commented on docs/api/speech_challenges.md
> +| `language`       | `string` | **Optional** Language of the challenge in ISO 639-2 format.                       |
```suggestion
| `language`       | `string` | **Required** Language of the challenge in ISO 639-2 format.                       |
```

2019-08-23 20:05 UTC, kvdb commented on docs/api/speech_challenges.md
> +| `topic`          | `string` | **Optional** A question or topic serving as guidance to the student. |
```suggestion
| `topic`          | `string` | **Required** A question or topic serving as guidance to the student. |
```

2019-08-23 20:05 UTC, kvdb commented on docs/api/speech_challenges.md
> +| `language`       | `string` | **Optional** Language of the challenge in ISO 639-2 format.          |
```suggestion
| `language`       | `string` | **Required** Language of the challenge in ISO 639-2 format.          |
```

2019-08-26 19:57 UTC, merged