docs(profile): add profile docs
itslanguage/itslanguage-docs pull request #39
Opened 2017-01-17 15:11 UTC by Lehren

Add documentation for profiles. Users can contain profiles.

2017-01-17 15:21 UTC, dcsiebe requested changes
Creating a profile is not documented? Also see the individual comments.

2017-01-17 15:21 UTC, dcsiebe commented on docs/api/profiles.md
> +together with a User.
Why create a profile with a user? Or do you mean that a profile always needs a user?

2017-01-17 15:21 UTC, dcsiebe commented on docs/api/profiles.md
> +GET /profiles/:profile HTTP/1.1
Why not `/user/profile`?

2017-01-17 15:21 UTC, dcsiebe commented on docs/api/profiles.md
> +List all profiles in the active organisation.
Is listing profiles necessary?

2017-01-17 15:21 UTC, dcsiebe commented on docs/api/users.md
> +groups       | `string[]` | **Optional** The groups this user is part of.
Groups is not part of the profile change, I'd rather see this in a separate commit.

2017-01-17 15:21 UTC, dcsiebe commented on docs/api/users.md
> +  "groups": ['GROUP_1'],
Same here

2017-01-17 15:21 UTC, dcsiebe commented on docs/api/users.md
> +  "groups": ['GROUP_1'],
Same here

2017-01-17 15:21 UTC, dcsiebe commented on docs/api/users.md
> +    "groups": ['GROUP_1'],
And here

2017-01-17 15:21 UTC, dcsiebe commented on docs/api/users.md
> +    "groups": ['GROUP_1'],
Also here

2017-01-17 15:21 UTC, dcsiebe commented on docs/api/users.md
> +  "groups": ['GROUP_1'],
And here

2017-01-17 15:24 UTC, Lehren commented on docs/api/profiles.md
> +together with a User.
Yeah a profile is useless without a containing user. So I guess the only way to make a profile is to have it be made together with a user. Unless we need functionality to also retroactively link a new profile to a profile-less user.

2017-01-17 15:25 UTC, Lehren commented on docs/api/profiles.md
> +GET /profiles/:profile HTTP/1.1
the `user/` link is only for the current user. Unless you mean `users/profile` which is a good suggestion.

You propose `users/:userId/profile` ?

2017-01-17 15:26 UTC, Lehren commented on docs/api/profiles.md
> +List all profiles in the active organisation.
Don't know yet. It would be nice to have in an eventual case. But if it's known that it is not neccessary I will take it out.

2017-01-17 15:27 UTC, dcsiebe commented on docs/api/profiles.md
> +GET /profiles/:profile HTTP/1.1
Both actually, currently the current user thing is good enough. I've also set up basicauths like that.

2017-01-17 15:29 UTC, dcsiebe commented on docs/api/profiles.md
> +together with a User.
I'd separate the profile creation from the user, i.e. require a separate api call. So a profile is not created together with a user.

2017-01-17 15:30 UTC, dcsiebe commented on docs/api/profiles.md
> +List all profiles in the active organisation.
I guess it's not needed at this point. @joggienl any thoughts about this?

2017-01-17 15:32 UTC, joggienl commented on docs/api/profiles.md
> +List all profiles in the active organisation.
A profile should be accessed through user, not directly. I don't see a case for just listing all profiles.

2017-01-17 15:32 UTC, Lehren commented on docs/api/profiles.md
> +together with a User.
If a profile is linked to a user with an existing profile, will it be overwritten or an error occurs?

2017-01-18 07:03 UTC, dcsiebe commented on docs/api/profiles.md
> +together with a User.
When creating a profile for a user that already has a profile, an error will be returned (status 409 with a json message stating the profile exists).

Url for the current user: `/user/profile`
Url for another user: `/users/:userid/profile`

2017-01-18 07:22 UTC, dcsiebe requested changes

2017-01-18 07:22 UTC, dcsiebe commented on docs/api/profiles.md
> +id           | `string`   | **Optional** A unique identifier. If none is given, one is generated.
Please remove the id, I'd like to keep this as an internal. Since profiles cannot be get by id, I think we should not export it to the user. Being able to set the id isn't necessary too when it isn't exported.

2017-01-18 07:22 UTC, dcsiebe commented on docs/api/profiles.md
> +  "id": "sdcjb823jhguys5j",
Also remove the id from the response, see the comment above.

2017-01-18 07:22 UTC, dcsiebe commented on docs/api/profiles.md
> +GET /user/profile/ HTTP/1.1
Please remove the trailing `/`.

2017-01-18 07:22 UTC, dcsiebe commented on docs/api/profiles.md
> +HTTP/1.1 201 Created
Since this is getting the profile, the status code should be 200 and not 201.

2017-01-18 07:22 UTC, dcsiebe commented on docs/api/profiles.md
> +GET /user/profile/ HTTP/1.1
Please remove the trailing `/`.

2017-01-18 07:22 UTC, dcsiebe commented on docs/api/profiles.md
> +GET /user/profile/ HTTP/1.1
Please remove the trailing `/`.

2017-01-18 07:22 UTC, dcsiebe commented on docs/api/profiles.md
> +HTTP/1.1 201 Created
Status code should be 200 since this is a GET.

2017-01-19 09:07 UTC, dcsiebe approved these changes

2017-01-19 09:08 UTC, merged