docs(profiles): cefr type updated to int
itslanguage/itslanguage-docs pull request #98
Opened 2018-12-10 10:45 UTC by macciocu

Continuation of preliminary closed MR: #96

As a first step to resolve https://gitlab.com/dcentralized/itslanguage/its-gae/issues/16, in this PR the profile API is re-added and the new spec. is implemented.

2018-12-11 08:26 UTC, joggienl requested changes
I've commented the requested changed in the code.
In short, the page was not updated to reflect the changes on `cefr` and `gender`.

2018-12-11 08:26 UTC, joggienl commented on docs/api/profiles.md
> +\*cefr       | `int`      | **Optional** The user's [CEFR (Common European Framework of Reference)](https://www.cambridgeenglish.org/exams-and-tests/cefr/) level.
I see `\*` before `cefr`, guess that slipped in?

2018-12-11 08:26 UTC, joggienl commented on docs/api/profiles.md
> +gender       | `string`   | **Optional** The user's gender ("m" = male, "f" = female).
When a user specifies, let's also allow `x`.

2018-12-11 08:26 UTC, joggienl commented on docs/api/profiles.md
> +### \*cefr
Here I see the `\*` again?

2018-12-11 08:26 UTC, joggienl commented on docs/api/profiles.md
> +gender       | `string`   | **Optional** The user's gender ("Male"|"Female").
This needs to be changed as well now.

2018-12-11 08:26 UTC, joggienl commented on docs/api/profiles.md
> +cefr         | `string`   | **Optional** The user's CEFR (Common European Framework of Reference) level.
This needs to be changed as well now.

2018-12-11 08:26 UTC, joggienl commented on docs/api/profiles.md
> +}
Example should reflect what we accept, I see `cefr` as string, and `gender` as complete string.

2018-12-11 08:26 UTC, joggienl commented on docs/api/profiles.md
> +  "updated": "2016-12-22T02:14:05Z"
Example should reflect what we accept, I see `cefr` as string, and `gender` as complete string.

2018-12-11 08:26 UTC, joggienl commented on docs/api/profiles.md
> +  "updated": "2017-01-03T12:16:55Z"
Example should reflect what we accept, I see `cefr` as string, and `gender` as complete string.

2018-12-11 08:26 UTC, joggienl commented on docs/api/profiles.md
> +  "updated": "2017-01-03T12:16:55Z"
Example should reflect what we accept, I see `cefr` as string, and `gender` as complete string.

2018-12-11 08:26 UTC, joggienl commented on docs/api/profiles.md
> +\*cefr       | `int`      | **Optional** The user's [CEFR (Common European Framework of Reference)](https://www.cambridgeenglish.org/exams-and-tests/cefr/) level.
Looking further, I also commented the same below. I think you wanted to make some kind of reference. I don't think that is needed because the text is directly below. You might want to simplify the link you added: remove that from the table and add it the the paragraph with the conversion table.

2018-12-11 08:32 UTC, macciocu commented on docs/api/profiles.md
> +\*cefr       | `int`      | **Optional** The user's [CEFR (Common European Framework of Reference)](https://www.cambridgeenglish.org/exams-and-tests/cefr/) level.
'\' is the escape character for '*', at least in my markdown preview editor it is necessary in order to visualize everything correctly.

2018-12-11 09:02 UTC, macciocu commented on docs/api/profiles.md
> +### \*cefr
Escape character for *

2018-12-11 09:08 UTC, joggienl commented on docs/api/profiles.md
> +\*cefr       | `int`      | **Optional** The user's [CEFR (Common European Framework of Reference)](https://www.cambridgeenglish.org/exams-and-tests/cefr/) level.
Yes indeed, it is an escape character. I'am unclear why you added it though, I think it does not add value to add this kind of a reference.

2018-12-11 09:10 UTC, joggienl commented on docs/api/profiles.md
> +### \*cefr
yeah i know, see comment above, I think it should be removed though.

2018-12-13 10:30 UTC, joggienl approved these changes

2018-12-13 10:30 UTC, merged